<<<<<<< HEAD
name: flutterapp
=======
name: meiapp
>>>>>>> 5ea17bf (commit)
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
=======
  http: ^1.3.0
>>>>>>> 5ea17bf (commit)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
